image:https://github.com/toedter/spring-hateoas-jsonapi/workflows/Build/badge.svg["build", link="https://github.com/toedter/spring-hateoas-jsonapi/actions"]
image:https://codecov.io/gh/toedter/spring-hateoas-jsonapi/branch/master/graph/badge.svg["coverage", link="https://codecov.io/gh/toedter/spring-hateoas-jsonapi"]
image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]

= JSON:API for Spring HATEOAS

This is an implementation of the media type `application/vnd.api+json` (JSON:API)
to be integrated in Spring HATEOAS. Goal is to use the existing Spring HATEOAS
representation models to serialize/deserialize them according to the JSON:API spec (see https://jsonapi.org/)

This project is in an early stage and work in progress, please stay tuned.

== Documentation

you can find a detailed documentation at https://toedter.github.io/spring-hateoas-jsonapi/

== Running the Example

* Make sure Java 8 or later JDK is installed
* Clone this Git repository and cd into `spring-hateoas-jsonapi`
* Open a terminal and invoke `./gradlew build bootrun` (just `gradlew` under Windows)
* Call endpoint link:++http://localhost:8080/api/movies?page[number]=0&page[size]=1++[++http://localhost:8080/api/movies?page[number]=0&page[size]=1++]
 with request header `Accept application/vnd.api+json`

The rendered result is:

[source,json]
{
  "jsonapi": {
    "version": "1.0"
  },
  "data": {
    "id": "1",
    "type": "movies",
    "attributes": {
      "title": "The Shawshank Redemption",
      "year": 1994,
      "rating": 9.3
    },
    "relationships": {
      "directors": {
        "data": {
          "id": "2",
          "type": "directors"
        }
      }
    },
    "links": {
      "self": "http://localhost:8080/api/movies/1",
      "movies": "http://localhost:8080/api/movies{?page[number],page[size]}"
    }
  },
  "included": {
    "id": "2",
    "type": "directors",
    "attributes": {
      "name": "Frank Darabont"
    }
  },
  "links": {
    "self": "http://localhost:8080/api/movies?page[number]=0,page[size]=1",
    "next": "http://localhost:8080/api/movies?page[number]=1&page[size]=1",
    "last": "http://localhost:8080/api/movies?page[number]=249&page[size]=1"
  },
  "meta": {
    "page-total-pages": 250,
    "page-size": 1,
    "page-number": 0,
    "page-total-elements": 250
  }
}


== License

Apache 2.0, see https://opensource.org/licenses/Apache-2.0
