image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]

= JSON:API for Spring HATEOAS

This is an implementation of the media type `application/vnd.api+json` (JSON:API)
to be integrated in Spring HATEOS. Goal is to use the existing Spring HATEOAS
representation models to serialize/deserialize them according to the JSON:API spec (see https://jsonapi.org/)

This project is at a very early stage and work in progress, please stay tuned.

== Getting Started

* Make sure Java 8 or later JDK is installed
* Open a terminal and invoke `./gradlew build bootrun` (just `gradlew` under Windows)
* Call endpoint link:++http://localhost:8080/api/movies?page[number]=0&page[size]=3++[++http://localhost:8080/api/movies?page[number]=0&page[size]=3++]
 with header `accept application/vnd.api+json`

The rendered result is (WIP):

[source,json]
{
    "jsonapi": {
        "version": "1.0"
    },
    "data": [
        {
            "id": "1",
            "type": "movies",
            "attributes": {
                "title": "The Shawshank Redemption",
                "year": 1994,
                "rating": 9.3
            },
            "relationships": {
                "directors": {
                    "data": {
                        "id": "2",
                        "type": "directors"
                    }
                }
            },
            "links": {
                "self": "http://localhost:8080/api/movies/1",
                "movies": "http://localhost:8080/api/movies{?page[number],page[size]}"
            }
        },
        {
            "id": "3",
            "type": "movies",
            "attributes": {
                "title": "The Godfather",
                "year": 1972,
                "rating": 9.2
            },
            "relationships": {
                "directors": {
                    "data": {
                        "id": "4",
                        "type": "directors"
                    }
                }
            },
            "links": {
                "self": "http://localhost:8080/api/movies/3",
                "movies": "http://localhost:8080/api/movies{?page[number],page[size]}"
            }
        },
        {
            "id": "5",
            "type": "movies",
            "attributes": {
                "title": "The Godfather: Part II",
                "year": 1974,
                "rating": 9.0
            },
            "relationships": {
                "directors": {
                    "data": {
                        "id": "4",
                        "type": "directors"
                    }
                }
            },
            "links": {
                "self": "http://localhost:8080/api/movies/5",
                "movies": "http://localhost:8080/api/movies{?page[number],page[size]}"
            }
        }
    ],
    "included": [
        {
            "id": "2",
            "type": "directors",
            "attributes": {
                "name": "Frank Darabont"
            }
        },
        {
            "id": "4",
            "type": "directors",
            "attributes": {
                "name": "Francis Ford Coppola"
            }
        }
    ],
    "links": {
        "self": "http://localhost:8080/api/movies?page[number]=0,page[size]=3"
    },
    "meta": {
        "page-total-pages": 84,
        "page-size": 3,
        "page-number": 0,
        "page-total-elements": 250
    }
}

== License

Apache 2.0, see https://opensource.org/licenses/Apache-2.0
