image:https://img.shields.io/badge/License-Apache%202.0-blue.svg["Apache 2.0", link="https://opensource.org/licenses/Apache-2.0"]

= JSON:API for Spring HATEOAS

This is an implementation of the media type `application/vnd.api+json` (JSON:API)
to be integrated in Spring HATEOS. Goal is to use the existing Spring HATEOAS
representation models to serialize/deserialize them according to the JSON:API spec (see https://jsonapi.org/)

This project is at a very early stage and work in progress, please stay tuned.

== Getting Started

* Make sure Java 8 or later JDK is installed
* Open a terminal and invoke `./gradlew build bootrun` (just `gradlew` under Windows)
* Call endpoint link:++http://localhost:8080/api/movies?page[number]=0&page[size]=1++[++http://localhost:8080/api/movies?page[number]=0&page[size]=1++]
 with header `accept application/vnd.api+json`



The result should be:

[source,json]
{
    "jsonapi": {
        "version": "1.0"
    },
    "data": {
        "id": "1",
        "type": "movies",
        "attributes": {
            "title": "The Shawshank Redemption",
            "year": 1994,
            "imdbId": "tt0111161",
            "rating": 9.3,
            "rank": 1
        },
        "links": {
            "self": "http://localhost:8080/api/movies/1",
            "directors": {
                "href": "http://localhost:8080/api/directors/2",
                "meta": {
                    "name": "Frank Darabont"
                }
            }
        }
    },
    "links": {
        "self": "http://localhost:8080/api/movies?page[number]=0,page[size]=1",
        "next": "http://localhost:8080/api/movies?page[number]=1&page[size]=1",
        "last": "http://localhost:8080/api/movies?page[number]=249&page[size]=1"
    },
    "meta": {
        "page-total-pages": 250,
        "page-size": 1,
        "page-number": 0,
        "page-total-elements": 250
    }
}

== License

Apache 2.0, see https://opensource.org/licenses/Apache-2.0
