:test-resources-dir: ../../../src/test/resources/com/toedter/spring/hateoas/jsonapi
:test-dir: ../../../src/test/java/com/toedter/spring/hateoas/jsonapi

[[client-side-support]]
= Client-Side Support

[[deserialization]]
== Deserialization

Simple JSON:API-based JSON structures can be deserialized, but only the generic Spring HATEOAS representation
models are supported.

For example, a JSON structured like

[source, json]
include::{test-resources-dir}/movieEntityModelWithLinks.json[]

would be deserialized to an object of class `EntityModel<Movie>`,
where the `Movie` class looks like

[source, java]
----
include::{test-dir}/support/Movie.java[tags=Movie]
----

Note that the deserialization mechanism is currently unable to deserialize all types of
complex JSON:API structures that can be built with the JSON:API model builder, but several features are already supported:

* Deserializing meta
* Deserializing included resources into the relationship DTOs

For example, a JSON like

[source, json]
include::{test-resources-dir}/moviesPagedJsonApiModelWithIncluded.json[]

would be deserialized into a `CollectionModel<EntityModel<MovieWithDirectors>>`, so that all the names
of the directors are set on the Java side.

NOTE: `CollectionModel<MovieWithDirectors>` would NOT resolve the director names, because deserialization
of JSON:API-specific features like relationships only works with Spring HATEOAS representation models.

For more examples of relationship deserialization, see the section <<server-deserialization>>.

[[rest-clients]]
== REST Clients

If you want to write a client that deserializes server responses into Java objects,
you can use Spring's HTTP client APIs with JSON:API support.

[[restclient]]
=== RestClient (Spring Boot 4+)

For Spring Boot 4 and later, use `RestClient` (which replaces `RestTemplate`):

[source,java, indent=0]
----
@Configuration
public class JsonApiClientConfig {

    @Bean
    public RestClient jsonApiRestClient(JsonApiConfiguration jsonApiConfiguration) {
        JsonMapper jsonMapper = jsonApiConfiguration.getJsonMapper();

        // Register JSON:API module
        Jackson2JsonApiModule jackson2JsonApiModule =
            new Jackson2JsonApiModule(jsonApiConfiguration);
        jsonMapper.registerModule(jackson2JsonApiModule);

        return RestClient.builder()
            .baseUrl("http://localhost:8080")
            .defaultHeader("Accept", "application/vnd.api+json")
            .messageConverters(converters -> {
                MappingJackson2HttpMessageConverter converter =
                    new MappingJackson2HttpMessageConverter();
                converter.setObjectMapper(jsonMapper);
                converter.setSupportedMediaTypes(
                    List.of(MediaType.parseMediaType("application/vnd.api+json"))
                );
                converters.add(0, converter);
            })
            .build();
    }
}
----

[[resttemplate]]
=== RestTemplate (Legacy)

For older Spring Boot versions, you can use RestTemplate with JSON:API configuration:

[source,java, indent=0]
----
include::{test-dir}/RestTemplateIntegrationTest.java[tags=restTemplateConfig]
----

NOTE: `RestTemplate` is in maintenance mode and will be removed in a future Spring Framework release.
For new applications using Spring Boot 4+, use `RestClient` instead.

[[postWithNoId]]
=== Creating POST requests without serialized JSON:API id

If you want to use RestTemplate to make a POST request, the JSON:API id is often created by the server
and is not included in the JSON body. The easiest way to achieve this is to configure a marker value to indicate
that DTOs with this id value should not include the JSON:API id in the resulting JSON.

For example, if you specify a configuration like
[source,java, indent=0]
----
include::{test-dir}/JacksonJsonApiIntegrationTest.java[tags=noIdMarker]
----
and create a Movie DTO with this id, like
[source,java, indent=0]
----
include::{test-dir}/JacksonJsonApiIntegrationTest.java[tags=noIdMovie]
----
the resulting JSON would look like
[source, json]
include::{test-resources-dir}/movieEntityModelWithoutId.json[]

[[traverson]]
== Traverson

The hypermedia type `application/vnd.api+json` is currently not compatible with the `Traverson`
implementation provided by {spring-hateoas-url}[Spring HATEOAS].

[[link-discovery]]
== Link Discovery

When working with hypermedia-enabled representations, a common task is to find a link with a particular relation
type in it.
{spring-hateoas-url}[Spring HATEOAS] provides JsonPath-based implementations of the `LinkDiscoverer` interface
for the configured hypermedia types.
When using this library, an instance supporting this hypermedia type (`application/vnd.api+json`)
is exposed as a Spring bean.

Alternatively, you can set up and use an instance as follows
(where `source` is the exact JSON you saw in the <<deserialization>> section):

[source,java, indent=0]
----
include::{test-dir}/JsonApiLinkDiscovererUnitTest.java[tags=link-discoverer]
----
