:resource-dir: json

[[introduction]]
= Introduction

[[fundamentals]]
== Fundamentals

JSON:API for Spring HATEOAS is based on version {spring-hateoas-version} of Spring HATEOAS.
For further understanding of this document, please be aware of both

* the {spring-hateoas-url}[Spring HATEOAS documentation]
* the https://jsonapi.org/format/[JSON:API Specification]

The following documentation assumes that the reader knows the above documents.
Some parts of the Java code examples are folded, click on the icon in the bottom-right corner
to expand the unfolded source code.

[[jsonapi]]
== JSON:API

https://jsonapi.org/[JSON:API] is a widely adapted hypermedia format.
You can find a list of implementations and tools https://jsonapi.org/implementations/[here].
Answers to a few questions, e.g. related to HAL, you can find
https://jsonapi.org/faq/#why-not-use-the-hal-specification[here].

Anytime a client supplies an `Accept` header with `application/vnd.api+json`, you can expect something like this:

[source, json]
----
include::{resource-dir}/jsonapi-sample.json[]
----

NOTE: The characters `[` and `]` in the Links section are unsafe and URL encoded when added automatically by the
library. So the URL decoded next link would look like: ++http://localhost:8080/api/movies?page[number]=1&page[size]=1++.
