[[mediatypes.jsonapi]]
= JSON:API
:code-dir: ../../../src/docs/java/com/toedter/spring/hateoas/jsonapi
:resource-dir: json
:test-dir: ../../../src/test/java/com/toedter/spring/hateoas/jsonapi
:test-resources-dir: ../../../src/test/resources/com/toedter/spring/hateoas/jsonapi
:example-code-dir: ../../../../example/src/main/java/com/toedter/spring/hateoas/jsonapi/example

https://jsonapi.org/[JSON:API] is a widely adapted hypermedia format.
You can find a list of implementations and tools https://jsonapi.org/implementations/[here].
Answers to a few questions, e.g. related to HAL, you can find
https://jsonapi.org/faq/#why-not-use-the-hal-specification[here].

Anytime a client supplies an `Accept` header with `application/vnd.api+json`, you can expect something like this:

[source, json]
----
include::{resource-dir}/jsonapi-sample.json[]
----

== Integration in your Backends

To enable the JSON:API media type you just need to add this module as a dependency to your project.

Maven:
[source,xml]
<dependency>
    <groupId>com.toedter</groupId>
    <artifactId>spring-hateoas-jsonapi</artifactId>
    <version>0.9.0</version>
</dependency>

Gradle:
[source]
implementation 'com.toedter:spring-hateoas-jsonapi:0.9.0'

The latest published snapshot version is `0.10.0-SNAPSHOT`.
If you want to try it out, please make sure to add https://oss.sonatype.org/content/repositories/snapshots/
as repository to your Maven or Gradle configuration.

== Representation Models

All Spring HATEOAS representation models are rendered as JSON:API.
Consider a simple Movie Class as base for a Spring HATEOAS entity model:

[source, java]
----
include::{test-dir}/support/Movie.java[tags=Movie]
----

An `EntityModel.of(new Movie("1", "Star Wars"))` is then rendered as

[source, json]
include::{test-resources-dir}/movieEntityModel.json[]

In JSON:API, the `id` field must be of type `String`.
But in your model you can use any Class and `toString()` is used for conversion.
So, if the `id` attribute of `Movie` would be of type `long`,
the rendered JSON:API would be the same.
The JSON:API `type` is automatically generated of the pluralized, lower case, simple class name.
This is best practice, since then most likely the type matches the URL (end)
of the corresponding REST collection resource.

NOTE: You can configure if you want to use non-pluralized class names, see <<configuration>>

== Annotations ==

The goal of this implementation is to automate the mapping from/to JSON:API
as convenient as possible for the developer.

There are 4 new Annotations provided by this project:

* `@JsonApiId` to mark a JSON:API `id`
* `@JsonApiType` to mark a field or method to provide a JSON:API `type`
* `@JsonApiTypeForClass` to mark class to provide a JSON:API `type`
** The JSON:API type is a required value of this annotation
* `@JsonApiRelationships` to mark a JSON:API `relationship`
** This annotation is not used for serialization but for deserialization,
see <<Creating>> for an example.

The use of these annotations is optional. For the mapping of the `id`, the
following rules apply in order:

* the annotation `@JsonApiId` is used on a field
* the annotation `@JsonApiId` is used on a method
* the annotation `@Id` (javax.persistence.Id) is used on a field
* the annotation `@Id` (javax.persistence.Id) is used on a method
* the entity (base for representation models) provides an attribute `id`

For the mapping of the `type`, the
following rules apply in order:

* the annotation `@JsonApiTypeForClass` is used on a class
* the annotation `@JsonApiType` is used on a field
* the annotation `@JsonApiType` is used on a method
* if no annotation is present, the pluralized, lower case, simple class name of the entity will be used

NOTE: You can configure if you want to use non-pluralized class names, see <<configuration>>

As an example, consider the class

[source, java]
----
include::{test-dir}/support/Movie2.java[tags=Movie]
----

Then, `EntityModel.of(new Movie2("1", "Star Wars", "my-movies")))` will be rendered as

[source, json]
----
include::{test-resources-dir}/movieEntityModelWithAnnotations.json[]
----

== JSON:API Builder ==

If you want to use JSON:API `relationships` or `included` data, you can use the
`JsonApiModelBuilder`. The following example shows how to create a JSON::API representation model using the `JsonApiModelBuilder`
[source, java]
----
import static com.toedter.spring.hateoas.jsonapi.JsonApiModelBuilder.jsonApiModel;
----

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=build-movie-model]
----

Consider that you want to express the relationships of movies to their directors.
A simple `Director` class could look like:

[source, java]
----
include::{test-dir}/support/Director.java[tags=Director]
----

You can build a relationship from a movie to a director like

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=build-relationship]
----

The representation model will be rendered as
[source, json, indent=0]
----
include::{test-resources-dir}/movieJsonApiModelWithRelationship.json[]
----

If you want the `directors` relationship always being rendered as an array,
even if it is empty or contains only a single data element,
you can build it like:

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=single-collection-relationship]
----

The representation model will be rendered as
[source, json, indent=0]
----
include::{test-resources-dir}/movieWithSingleCollectionRelationship.json[]
----

You can also pass a Java `Collection` as data for a relationship.
A collection will always be rendered as JSON array,
even when it is empty or contains a single element.
So,

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=single-collection-relationship2]
----

would be rendered exactly like the previous example.

The builder also provides methods for adding links and meta to a relationship.
Check out the link:../api/com/toedter/spring/hateoas/jsonapi/JsonApiModelBuilder.html[Javadoc API documentation]
for more details.

If you want to include the related resources in the JSON:API output,
you can build included `director` resources like:

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=build-included]
----

The representation model will be rendered as
[source, json, indent=0]
----
include::{test-resources-dir}/movieJsonApiModelWithManyRelationshipsAndIncluded.json[]
----

The following example shows the creation of a more complex
JSON:API specific representation model with a paged model as base.
The builder supports adding both pagination metadata and pagination links.

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=complex-paged-model]
----

This model will be rendered as

[source, json]
----
include::{test-resources-dir}/moviesPagedJsonApiModelWithIncluded.json[]
----

[[Inclusion]]
== Inclusion of related Resources ==

There is no direct support for including related resources,
but a REST controller could provide an optional request parameter like

[source, java]
@RequestParam(value = "included", required = false) String[] included)

Then, within the controller implementation, this parameter could be interpreted,
and the builder could be used for the inclusion, like

[source, java, indent=0]
----
include::{example-code-dir}/movie/MovieController.java[tags=relationship-inclusion]
----

[[SparseFielsets]]
== Sparse Fieldsets ==

Sparse fieldsets are supported for attributes within `data` and `included`. You can add sparse fieldsets
by using the `JsonApiBuilder`. The following example illustrates the build, assuming a director would have
the attributes `name` and `born`, and a movie would have the attributes `title` and `rating`.

[source, java, indent=0]
----
include::{test-dir}/JsonApiModelBuilderIntegrationTest.java[tags=sparse-fieldset]
----

So, only the name attribute of a director, and the title attribute
of a movie would be serialized:

[source, json]
----
include::{test-resources-dir}/directorWithSparseFieldsetOnIncluded.json[]
----

In a REST controller, a method with HTTP-mapping could provide an optional request attribute for each sparse fieldset
that should be applied to a specific JSON:API type, like:

[source, java]
@RequestParam(value = "fields[movies]", required = false) String[] fieldsMovies,
@RequestParam(value = "fields[directors]", required = false) String[] fieldsDirectors)

In the following controller code, you could check the existence of these request parameters, like:

[source, java]
if (fieldsDirectors != null) {
    builder = builder.fields("directors", fieldsDirectors);
}

When adding sparse fieldsets to the builder, they will NOT automatically exclude added relationships.
Relationships have to be added conditionally, like the inclusions, for example:

[source, java]
if (fieldsDirectors == null || Arrays.asList(fieldsDirectors).contains("movies")) {
    builder = builder.relationship("movies", director.getMovies());
}

[[Creating]]
== Creating Resources with HTTP POST ==

To create new REST resources using HTTP POST, you can provide `JSON:API` formatted JSON as input.
For example, a `POST` with the body:

[source, json]
----
include::{test-resources-dir}/postMovie.json[]
----

will be deserialized to an `EntityModel<Movie>` automatically.
You can also create REST resources that contain `JSON:API relationships`.
You just have to annotate the underlying domain model class, with `JsonApiRelationships(<relationship name>)`

For example, a `POST` with the body:

[source, json]
----
include::{test-resources-dir}/postMovieWithTwoRelationships.json[]
----

will be deserialized to an `EntityModel<Movie>` with a filled list of directors,
where ONLY the id attribute of each director is set.
The REST controller then has to interpret those relationships and bind the
real director objects to the movie.

Here is an example of a class using the annotation:

[source, java]
----
include::{test-dir}/support/MovieWithDirectors.java[tags=Movie-with-directors]
----

NOTE: If you use the annotation `JsonApiRelationships` on an attribute of a Java class,
the content will NOT be serialized automatically to `JSON:API relationships`. This is on purpose,
please us the `JsonApiModelBuilder` to decide, which relationships and included objects you want to return.

[[polymorphy]]
== Polymorphic Deserialization ==

You can configure polymorphic deserialization on a 'per class' base,
using some Jackson annotations. The following example illustrates this:

Imagine a controller method like
[source, java]
@PostMapping("/movies")
public ResponseEntity<?> newMovie(@RequestBody EntityModel<Movie> movie) { ...

and a subclass of `Movie` that contains a rating, like
[source, java]
@NoArgsConstructor
@Data
@JsonApiTypeForClass("movies")
public class MovieWithRating extends Movie {
    private double rating;
}

You could now annotate the `Movie` class with:
[source, java]
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME)
@JsonSubTypes({
    @JsonSubTypes.Type(value = MovieWithRating.class, name = "movieWithRating")
})

Then a HTTP POST to /movies with body
[source, json]
----
include::{test-resources-dir}/postMovieWithRating.json[]
----

would be deserialized to an object of class `MovieWithRating`, even though the controller
method accepts the superclass `Movie`.

NOTE: @-members will be introduced in JSON:API version 1.1.
The above example will produce JSON that is not compliant with JSON:API 1.0.
For JSON:API 1.0 compliance you could configure Jackson like
`@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, property = "typeName")` instead.

Important: The above mechanism is only used for deserialization, NOT for serialization, since the
JSON:API specification uses the `type` attribute (within data) for the same purpose.
So the JSON of the serialized Java object (of class `MovieWithRating`) would then look like:

[source, json]
----
include::{test-resources-dir}/polymorphicMovie.json[]
----


[[configuration]]
== Configuration ==

There are several options how to change the output of the JSON:API rendering.

For a specific JSON:API configuration, you can create a Spring bean of type JsonApiConfiguration.
Currently, you can configure

* if the JSON:API version should be rendered automatically, the default is `false`.
* if JSON:API types should be rendered as pluralized or non pluralized class names.
** The default is pluralized.
* if JSON:API types should be rendered as lower cased or original class names.
** The default is lower cased.
* if page information of a PagedModel should be rendered automatically as JSON:API meta object.
** The default is `true`.
* if a specific Java class should be rendered with a specific `JSON:API type`. This is useful when
representation model classes should get the `JSON:API type` of the domain model or when derived classes
should get the `JSON:API type` of the super class. See example below.
* A lambda expression to add additional configuration to the Jackson `ObjectMapper` used for serialization.

NOTE: Since the JSON:API recommendation contains square brackets in the request parameter names,
make sure you provide the following configuration in your Spring `application.properties` when using Tomcat:
`server.tomcat.relaxed-query-chars= [,]`

Here is an example how you would implement a JSON:API configuration:

[source, java, indent=0]
----
include::{test-dir}/JsonApiWebMvcWithConfigIntegrationTest.java[tags=jsonApiConfig]
----

[[errors]]
== Error Handling ==

To create `JSON:API` compliant error messages, you can use `JsonApiErrors` and `JsonApiError`

Here is an example how to produce an error response:

[source, java, indent=0]
----
include::{test-dir}/support/WebMvcMovieController.java[tags=errors-builder]
----

The result would be rendered as:

[source, json]
----
include::{test-resources-dir}/errorsMvcExample.json[]
----














