[[mediatypes.jsonapi]]
= JSON:API
:code-dir: ../../../src/docs/java/com/toedter/spring/hateoas/jsonapi
:resource-dir: json
:test-dir: ../../../src/test/java/com/toedter/spring/hateoas/jsonapi
:test-resources-dir: ../../../src/test/resources/com/toedter/spring/hateoas/jsonapi
:linkattrs:
:tabsize: 2


https://jsonapi.org/[JSON:API] is a widely adapted hypermedia format.
You can find a list of implementations and tools https://jsonapi.org/implementations/[here].
Answers to a few questions, e.g. related to HAL, you can find
https://jsonapi.org/faq/#why-not-use-the-hal-specification[here].

To enable JSON:API to Spring Hateoas, just put com.toedter.spring.hateoas.jspnapi.{version}.jar in your classpath.

Anytime a client supplies an `Accept` header with `application/vnd.api+json`, you can expect something like this:

[source, json]
include::{resource-dir}/jsonapi-sample.json[]

== Spring HATEOAS Representation Models

All Spring HATEOAS representation models are rendered as JSON:API.
Consider a simple Movie Class as base for Spring HATEOAS representation model.:

[source, java]
include::{test-dir}/support/Movie.java[tags=Movie]

An `EnitiyModel.of(new Movie("1", "Star Wars"))` is then rendered as

[source, json]
include::{test-resources-dir}/movieEntityModel.json[]

In JSON:API, the `id` field must be of type `String`.
But in your model you can use any Class and `toString()` is used for conversion.
So, if the `id` attribute of `Movie` would be of type `long`,
the rendered JSON:API would be the same.
The JSON:API `type` is automtically generated of the pluralized, uncapitalized simple class name.
This is best practice, since then most likely the type matches the URL (end) of a REST collection resource.

NOTE: It is planned to make this configurable in the future

== Use of Annotations ==

The goal of this implementation is to automate the mapping from/to JSON:API
as convenient as possible for the developer. For the mapping of the ´id´, the
following rules apply in the following order:

* the annotation `@JsonApiId` is used on a field
* the annotation `@JsonApiId` is used on a method
* the annotation `@Id` (javax.persistence.Id) is used on a field
* the annotation `@Id` (javax.persistence.Id) is used on a method
* the entity (base for representation models) provides an attribute `id`

For the mapping of the ´type´, the
following rules apply in the following order:

* the annotation `@JsonApiType` is used on a field
* if no annotation is present, the pluralized, uncapitalized simple class name of the entity will be used

NOTE: It is planned to make this configurable in the future

As an example, consider the class

[source, java]
include::{test-dir}/support/Movie2.java[tags=Movie]

Then, `EntityModel.of(new Movie2("1", "Star Wars", "my-movies")))` will be rendered as

[source, json]
include::{test-resources-dir}/movieEntityModelWithAnnotations.json[]

== JSON:API Builder ==

If you want to use JSON:API `relationships` or `included` data, you can use the
`JsonApiModelBuilder`. The following example shows the creation of a more complex
representation model.

Consider that you want to express the relationships of movies to their directors.
A simple `Director` class could look like:

[source, java]
include::{test-dir}/support/Director.java[tags=Director]

The following example shows the creation of a more complex
JSON:API specific representation model:

[source, java]
include::{test-dir}/JsonApiModelBuilderTest.java[tags=complex-paged-model]

This model will be renderd as

[source, json]
include::{test-resources-dir}/moviesPagedJsonApiModelWithIncluded.json[]













